name: vuln workflow_run

on:
    workflow_run:
        workflows:
            ["attacker defined"]
        types:
            - completed

jobs:
    firstjob:
        runs-on: ubuntu-24.04
        steps:
            - name: debug context
              run: |
               echo "sha: ${{github.event.pull_request.head.sha}}"
               echo "github sha ${{github.sha}}"
               echo "Repository: ${{ github.repository }}"
               echo "Repository owner: ${{ github.repository_owner }}"
               echo "Repository name: ${{ github.event.repository.name }}"
               echo "Full repo URL: ${{ github.repositoryUrl }}"
               echo "Actor: ${{ github.actor }}"
               echo "Triggering actor: ${{ github.triggering_actor }}"
               echo "Token permissions (read from job context):"
               echo "Contents: ${{ toJSON(github.event.repository.permissions) }}"